sudo: required
services: 
  - docker

before_install:
  - docker build -t chejerlakarthik/docker-react -f Dockerfile.dev .

script:
  - docker run chejerlakarthik/docker-react "npm run test -- --coverage"
